#spring.application.name=Producer-app

spring:
  application:
    name: Producer-app
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
        retries: 5

crm:
  url: http://crm-mock:8080
  fetch-rate-ms: 60000  # fetch every 60 seconds

inventory:
  url: http://inventory-mock:8080
  fetch-rate-ms: 60000  # fetch every 60 seconds

logging:
  level:
    org.springframework.web: INFO
    com.example.producer: DEBUG

